### ISSUE TITLE
Is there an easy way to not use hash history?

### ISSUE THREAD

**Issue by juliomarcos** [TylorS/cyclic-router#3]
If not, how could I do this?

Thanks

**Comment by TylorS** [comment]
```js
import {makeRouterDriver} from 'cyclic-router'
import {makeHistoryDriver, supportsHistory} from 'cyclic-history'
import {createHashHistory, createHistory} from 'history'

const history = supportsHistory() ?
  createHistory() : createHashHistory()

const historyDriver = makeHistoryDriver(history)

run(main, {router: makeRouterDriver(historyDriver)})
```

**Comment by juliomarcos** [comment]
That part I've managed to do. But how should filter my links?

**Comment by TylorS** [comment]
Creating them should be exactly the same. What do you mean by filtering your links?

**Comment by maximilianmikus** [comment]
If I click an internal link using `createHistory` instead of `createHashHistory`, client side routing is not used. What am I missing?

**Comment by TylorS** [comment]
You'll have to use a preventDefault driver to keep from redirecting normally. 

I've added a feature to automatically capture link clicks to @motorcycle/router that is 100% optional.
It's something I could add here. The downside is you lose some of the usefulness of the history API. 
e.g. Setting state

**Comment by maximilianmikus** [comment]
If it is optional, why not. I would try it out.

**Comment by TylorS** [comment]
@maximilianmikus I'll try to add this feature soon.

**Comment by maximilianmikus** [comment]
Just for future reference: You can use `makeRouterDriver(history, {capture: true})`
