### ISSUE TITLE
Programmatically change route.

### ISSUE THREAD

**Issue by kliron** [TylorS/cyclic-router#7]
Thank you for your work. Is there any support or plans to support changing route programmatically?

**Comment by TylorS** [comment]
Yes, the sink works exactly like @cycle/history.

```js
function main(sources) {
  return {
    router: Observable.just('/path')
  }
}
```

**Comment by TylorS** [comment]
Here is the relevant piece of documentation on it : http://cycle.js.org/history/docs/#historyDriver

**Comment by kliron** [comment]
Perfect, thanks. Closing this.
