### ISSUE TITLE
Add example using cycle/http

### ISSUE THREAD

**Issue by mciparelli** [TylorS/cyclic-router#8]
This is a suggestion to add a code example of cyclic-router + cycle/http

**Comment by nakaji-dayo** [comment]
I tried making example.
@TylorS  Could you check whether my code is right?

https://github.com/nakaji-dayo/cyclic-router/commit/81cf24615db54f42a6379229e63ccd80b734704c

**Comment by TylorS** [comment]
@nakaji-dayo That looks correct to me :+1:

**Comment by nakaji-dayo** [comment]
@TylorS Thank you!

**Comment by TylorS** [comment]
Thank you @nakaji-dayo! I make minor adjustment for it to run on the gh-pages as well [here](https://tylors.github.io/cyclic-router/example/)
